site_name: Þórarinn Bjartur Breiðfjörð
site_description: Make First Fix Later
site_url: https://hanndoddi.com

theme:
  name: material
  logo: assets/logo/hanndoddilogo.svg
  favicon: assets/logo/favicon/favicon.png
  language: en

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      primary: custom
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/js/external-links.js


plugins:
#  - social
  - search
# - tags
# - tags:
#      tags_file: tags.md
  - blog:
      blog_dir: journal
      blog_toc: true
      post_url_format: "{slug}"

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hanndoddi
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/hanndoddi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hanndoddi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hanndoddi
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hanndoddi

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: |
  &copy; 2024 <a href="https://github.com/hanndoddi"  target="_blank" rel="noopener">hanndoddi</a>  <br>   Made first with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material for MkDocs</a>,
  then fixed later by <strong>hanndoddi</strong>    
