authors:
  Þórarinn:
    name: Þórarinn Bjartur Breiðfjörð
    description: Creator
    avatar: ../assets/thorarinn_bb_826x827px.jpeg
   # url: https://www.youtube.com/@james-willett?sub_confirmation=1
